"""Build a top-level ``plan.csv`` by laying a grid over a world map.

This is the step between ``bootstrap_from_png`` (which renders the scaled world map) and
``orchestrate prepare`` (which builds the level packages). It was missing: the original
sunspine plan was generated by throwaway code in a session and never saved, so when the grid
needed changing there was nothing to change. See ``GRID_PLAN_NOTES.md`` for the whole chain.

What it does, derived from the plan it has to reproduce:

  1. lay a cols x rows lattice over the map, cells tiling it exactly
  2. intersect each cell with the painted land -- interior cells come out as plain rectangles,
     cells on the coast get clipped to the shoreline, which is where the 3-6 point polygons
     and slanted edges in the original come from
  3. drop cells with no land in them (6 of 30 in the 6x5 sunspine plan)
  4. that intersection is the CORE polygon: the level's own ground
  5. dilate it by ``--overlap-buffer`` to get the GENERATION polygon: core plus the margin a
     neighbour's padding is cut from
  6. the CROP is the generation polygon's bounding box grown by ``--crop-margin``, which was
     exactly 4px on every row of the original
  7. two levels are connected when their generation polygons overlap

The canvas is not written here -- it is reported, because it belongs in the run config. It is
the largest crop with each edge rounded up to gpt-image-2's 16px multiple.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from tools.painted_map_pipeline.openai_api import (  # noqa: E402
    EDGE_MULTIPLE,
    MAX_EDGE,
    MAX_PIXELS,
)
from tools.painted_map_pipeline.world_levels import geometry  # noqa: E402

Image.MAX_IMAGE_PIXELS = None

# The original plan's constants, kept as defaults so a re-run reproduces it.
DEFAULT_OVERLAP_BUFFER = 150
DEFAULT_CROP_MARGIN = 4
# A cell can clip a sliver of coastline barely worth a level of its own. The original 6x5 plan
# dropped one of ~10.6k px while keeping its smallest real level at 449k, so a filter existed
# somewhere between; 1% of a cell is comfortably inside that gap.
DEFAULT_MIN_AREA_FRAC = 0.01


def clip_to_rect(polygon, left, top, right, bottom, include=None):
    """The part of a polygon inside an axis-aligned rectangle, as a list of vertices.

    Exact arithmetic on the landmass polygon from ``snap_landmass``, not a re-trace of pixels.
    That is the whole point: tracing the coast separately for the core and for the generation
    quantises the same diagonal over two different x-ranges, so the two lines end up a fraction
    of a pixel apart and the core leaks outside the generation -- 1367px of it on level 05.
    Clipping one polygon twice cuts the identical line equations both times, so the core is
    inside the generation by construction.

    shapely rather than a hand-rolled Sutherland-Hodgman: the landmass is concave, and a cell
    straddling the notch can cut it into two pieces, which the textbook algorithm joins with a
    degenerate bridge instead of reporting honestly. Here the largest piece is taken.
    """
    from shapely.geometry import Polygon, box

    shape = Polygon(polygon)
    if not shape.is_valid:
        shape = shape.buffer(0)
    piece = shape.intersection(box(left, top, right, bottom))
    if piece.is_empty:
        return []
    if piece.geom_type == "MultiPolygon":
        piece = max(piece.geoms, key=lambda g: g.area)
    if include is not None:
        # Union with the already-rounded core, so the generation contains it exactly.
        #
        # Both polygons cut the same coast line, so mathematically the core is inside the
        # generation -- but plan.csv stores integer pixels, and rounding each vertex
        # independently moves it up to half a pixel, which is enough for a core corner to land
        # outside a generation edge it sits exactly on. Unioning in the finished integer core
        # makes containment true by construction instead of true within a tolerance.
        piece = piece.union(Polygon(include))
        if piece.geom_type == "MultiPolygon":
            piece = max(piece.geoms, key=lambda g: g.area)
    if piece.geom_type != "Polygon":
        return []
    return list(piece.exterior.coords)[:-1]


def buffer_polygon(polygon, distance, bounds=None, within=None, include=None):
    """The polygon grown outward by ``distance``, edges kept straight.

    Mitre join: the default rounded join turns every corner into an arc of dozens of vertices.
    """
    from shapely.geometry import Polygon

    shape = Polygon(polygon)
    if not shape.is_valid:
        shape = shape.buffer(0)
    grown = shape.buffer(distance, join_style=2)
    if within is not None:
        # Also cut to the landmass. Without it the growth runs past the coast into black and
        # the mask asks the model to paint empty space -- on level 01 the mask covered 67.2%
        # of the canvas against 57.3% of actual terrain, and every unpainted fringe pixel
        # counts against cut_iou. Safe: the core is itself a clip of this same landmass, so
        # it stays inside.
        grown = grown.intersection(Polygon(within))
    if bounds is not None:
        # The buffer runs off the map at the edges and the plan may not name coordinates
        # outside it. Safe to clip: the core is inside the map by construction, so trimming
        # the grown shape to the map cannot cut into it.
        from shapely.geometry import box

        grown = grown.intersection(box(*bounds))
    if include is not None:
        # Union the already-rounded core back in, last. Clipping to the landmass puts the
        # coast back on both polygons as a shared edge, and rounding each vertex to a whole
        # pixel independently can then pull the generation a fraction inside the core. Adding
        # the finished integer core makes containment exact rather than nearly exact.
        grown = grown.union(Polygon(include))
    if grown.geom_type == "MultiPolygon":
        grown = max(grown.geoms, key=lambda g: g.area)
    # One pixel, applied last. Vertices are about to be rounded to whole pixels, which can move
    # an edge inward by up to half a pixel per axis; a polygon sharing the coastline with the
    # core can lose containment that way, and prepare rejects the level. This is the rounding
    # error itself rather than a guessed tolerance, and it only enlarges a padding region.
    grown = grown.buffer(1.0, join_style=2)
    if grown.geom_type == "MultiPolygon":
        grown = max(grown.geoms, key=lambda g: g.area)
    return list(grown.exterior.coords)[:-1]


def _round(points):
    """Round to whole pixels and drop consecutive duplicates. Every corner is kept."""
    out = []
    for x, y in points:
        q = (int(round(x)), int(round(y)))
        if not out or out[-1] != q:
            out.append(q)
    if len(out) > 1 and out[0] == out[-1]:
        out.pop()
    return out


def _cell_bounds(index: int, count: int, extent: int) -> tuple[int, int]:
    """Cell edges that tile the extent exactly, even when it does not divide evenly.

    The floor-based split ``export_painted_grid`` uses: 7 columns over 18150px gives cells of
    2592 and 2593 rather than a 6px strip left over at the right edge.
    """
    return index * extent // count, (index + 1) * extent // count - 1


def _area(points) -> float:
    n = len(points)
    return abs(sum(points[i][0] * points[(i + 1) % n][1] - points[(i + 1) % n][0] * points[i][1]
                   for i in range(n))) / 2.0


def _encode(points) -> str:
    return "|".join(f"{int(round(x))}:{int(round(y))}" for x, y in points)


def build_plan(
    world_map: Path,
    landmass_polygon: list,
    *,
    cols: int,
    rows: int,
    overlap_buffer: int = DEFAULT_OVERLAP_BUFFER,
    crop_margin: int = DEFAULT_CROP_MARGIN,
    min_area_frac: float = DEFAULT_MIN_AREA_FRAC,
    region: str = "",
    name_prefix: str = "Level",
) -> tuple[list[dict], tuple[int, int]]:
    """Arithmetic on one polygon. The image is opened only to learn its size.

    Per cell:

        core       = landmass polygon  clipped to the cell rectangle
        generation = core grown by overlap_buffer, clipped to the expanded cell rectangle
        crop       = generation's bounding box, plus crop_margin, clamped to the map

    Both polygons come from the same landmass polygon, and the generation is grown FROM the
    core, so the core is inside it by construction. That matters: deriving the two
    independently -- tracing land inside the cell, then tracing land inside the expanded cell
    -- quantises the same coastline over two different ranges, and prepare rejects the pair
    with "core polygon is not contained by generation polygon". Growing one from the other has
    nothing to reconcile.

    Run ``snap_landmass`` first: this needs a coastline that IS a polygon.
    """
    with Image.open(world_map) as opened:
        width, height = opened.size
    coast = [tuple(map(float, point)) for point in landmass_polygon]
    min_area = (width / cols) * (height / rows) * min_area_frac

    specs: list[dict] = []
    for row in range(rows):
        top, bottom = _cell_bounds(row, rows, height)
        for col in range(cols):
            left, right = _cell_bounds(col, cols, width)

            clipped = clip_to_rect(coast, left, top, right, bottom)
            if len(clipped) < 3:
                continue
            core = _round(clipped)
            if len(core) < 3 or _area(core) < min_area:
                continue                       # no land here, or only a sliver of it

            el, et = max(0, left - overlap_buffer), max(0, top - overlap_buffer)
            er, eb = (min(width - 1, right + overlap_buffer),
                      min(height - 1, bottom + overlap_buffer))
            # Clipped to the expanded cell rather than only to the map: without it the growth
            # bulges past the coast in every direction and the crops, and so the canvas, grow
            # past what gpt-image-2 accepts.
            generation = _round(
                buffer_polygon(core, overlap_buffer,
                               bounds=(el, et, er, eb), within=coast,
                               include=core)
            )
            if len(generation) < 3:
                continue

            gl, gt, gr, gb = geometry.polygon_bbox(tuple(generation))
            cx0, cy0 = max(0, gl - crop_margin), max(0, gt - crop_margin)
            cx1, cy1 = min(width - 1, gr + crop_margin), min(height - 1, gb + crop_margin)
            specs.append({
                "cell": (col, row),
                "core": core,
                "generation": generation,
                "crop": (cx0, cy0, cx1 - cx0 + 1, cy1 - cy0 + 1),
                "gen_bbox": (gl, gt, gr, gb),
            })

    for index, spec in enumerate(specs, start=1):
        spec["id"] = f"{index:02d}"
        spec["name"] = f"{name_prefix} {index:02d}"
    # Orthogonal grid neighbours whose generation polygons actually meet. Orthogonality alone
    # is wrong -- in the 6x5 plan, cells (3,1) and (4,1) are side by side but their land is
    # 2052px apart, and the original does not link them. Overlap alone is wrong too: it links
    # diagonal cells whose padded boxes clip at a corner, which the original never does.
    by_cell = {spec["cell"]: spec for spec in specs}
    for spec in specs:
        al, at, ar, ab = spec["gen_bbox"]
        col, row = spec["cell"]
        links = []
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            other = by_cell.get((col + dx, row + dy))
            if other is None:
                continue
            bl, bt, br, bb = other["gen_bbox"]
            if al <= br and bl <= ar and at <= bb and bt <= ab:
                links.append(other["id"])
        spec["connections"] = sorted(links)

    rows_out = [{
        "id": s["id"], "name": s["name"], "region": region,
        "crop_x_px": s["crop"][0], "crop_y_px": s["crop"][1],
        "crop_width_px": s["crop"][2], "crop_height_px": s["crop"][3],
        "overlap_buffer_px": overlap_buffer,
        "core_polygon_points_px": _encode(s["core"]),
        "generation_polygon_points_px": _encode(s["generation"]),
        "connections": ";".join(s["connections"]),
    } for s in specs]

    def up16(value: int) -> int:
        return -(-value // EDGE_MULTIPLE) * EDGE_MULTIPLE

    canvas = (up16(max(s["crop"][2] for s in specs)),
              up16(max(s["crop"][3] for s in specs)))
    return rows_out, canvas


FIELDS = [
    "id", "name", "region", "crop_x_px", "crop_y_px", "crop_width_px", "crop_height_px",
    "overlap_buffer_px", "core_polygon_points_px", "generation_polygon_points_px",
    "connections",
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("world_map", help="Scaled world map PNG (output of bootstrap_from_png).")
    parser.add_argument("--cols", type=int, required=True)
    parser.add_argument("--rows", type=int, required=True)
    parser.add_argument("--out", required=True, help="Where to write plan.csv.")
    parser.add_argument("--region", default="")
    parser.add_argument("--name-prefix", default="Level")
    parser.add_argument("--overlap-buffer", type=int, default=DEFAULT_OVERLAP_BUFFER,
                        help="Padding margin a neighbour inherits. The original used 150.")
    parser.add_argument("--crop-margin", type=int, default=DEFAULT_CROP_MARGIN,
                        help="Slack around the generation polygon's box. The original used 4.")
    parser.add_argument("--landmass-polygon", required=True,
                        help="JSON from snap_landmass. The coastline must already be a "
                             "polygon; everything here is clipping it.")
    parser.add_argument("--overlay", default=None,
                        help="Also write the labelled review overlay here. Always look at it: "
                             "a plan is easy to read wrong as numbers and obvious as a picture.")
    parser.add_argument("--min-area-frac", type=float, default=DEFAULT_MIN_AREA_FRAC,
                        help="Skip a cell whose land is under this fraction of a cell's area.")
    args = parser.parse_args()

    rows, canvas = build_plan(
        Path(args.world_map),
        json.loads(Path(args.landmass_polygon).read_text())["polygon"],
        cols=args.cols,
        rows=args.rows,
        overlap_buffer=args.overlap_buffer,
        crop_margin=args.crop_margin,
        min_area_frac=args.min_area_frac,
        region=args.region,
        name_prefix=args.name_prefix,
    )
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(rows)

    if args.overlay:
        # Same overlay `prepare` writes, from the same function, so the two cannot disagree.
        from tools.painted_map_pipeline.world_levels.package_builder import draw_plan_overlay
        from tools.painted_map_pipeline.world_levels.plan_loader import load_level_plan

        with Image.open(args.world_map) as opened:
            world = opened.convert("RGBA")
        overlay = Path(args.overlay)
        overlay.parent.mkdir(parents=True, exist_ok=True)
        draw_plan_overlay(world, load_level_plan(out, world.size)).convert("RGB").save(overlay)
        print(f"  overlay: {overlay}")

    pixels = canvas[0] * canvas[1]
    print(f"wrote {len(rows)} levels to {out}")
    print(f"  grid {args.cols}x{args.rows} = {args.cols * args.rows} cells, "
          f"{args.cols * args.rows - len(rows)} empty")
    print(f"  canvas for the run config: {canvas[0]}x{canvas[1]} = {pixels / 1e6:.2f} MP")
    if pixels > MAX_PIXELS or max(canvas) > MAX_EDGE:
        print(f"  WARNING: exceeds gpt-image-2 limits "
              f"({MAX_PIXELS / 1e6:.1f} MP, {MAX_EDGE}px edge). Use more cells.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
